CREATE DATABASE IF NOT EXISTS BD_EST_SUPER;
USE BD_EST_SUPER;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    QUALIDADE VARCHAR(100) NOT NULL,
    PRECO DOUBLE NOT NULL,
    FK_ID_CATEGORIA INT, 
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS PRODUTO_FORNECEDOR(
	CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    FK_ID_PRODUTO INT, 
    FK_CNPJ_FORNECEDOR VARCHAR(14),
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTO(ID),
    FOREIGN KEY (FK_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ)
);