CREATE DATABASE IF NOT EXISTS BD_MUSICA;
USE BD_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF_CNPJ VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    RITMO VARCHAR(50) NOT NULL,
    ESTILO VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DURACAO VARCHAR(50) NOT NULL,
    CAPA BLOB NOT NULL,
    FK_CPF_CNPJ_ARTISTA VARCHAR(14),
    FOREIGN KEY (FK_CPF_CNPJ_ARTISTA) REFERENCES ARTISTA(CPF_CNPJ)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    LETRA VARCHAR(1000) NOT NULL,
    DURACAO VARCHAR(50) NOT NULL,
    FK_CPF_CNPJ_ARTISTA VARCHAR(14),
    FK_ID_GENERO INT,
    FOREIGN KEY (FK_CPF_CNPJ_ARTISTA) REFERENCES ARTISTA(CPF_CNPJ),
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO(ID)
);